typography_spectrum: 0.2465471
color:
  saturation: 0.5701519
  lightness: 0.105648
  brandStrength: 0.559176
  brandColors:
    - '#FDFDFD'
    - '#890000'
    - '#0E0000'
    - '#EBA277'
    - '#BB6743'
  rhythmicContrast: 0.0319863
layout_spectrum: 0.5191159
name: 'roxanarahnama '
title: ROXANA RAHNAMA
description: Actress & Filmmaker
